#!/bin/sh

# Startup script for PRISM GUI (Linux/Solaris)

# PRISM home directory
PRISM_DIR="/Users/ariannabianchi/Desktop/prism-4.8.1-mac64-x86.2"

# Launch using main PRISM script
PRISM_MAINCLASS=userinterface.GUIPrism
PRISM_HEADLESS=false
export PRISM_MAINCLASS PRISM_HEADLESS
$PRISM_DIR/bin/prism "$@"
